### ISSUE TITLE
Número de colaboradores

### ISSUE THREAD

**Issue by lauramcastro** [angelcastro2/PracticaVVS#1]
Aínda que os tres fixestes commits, un dos membros do equipo non aparece como colaborador, o usuario dos seus commits non se identifica correctamente como un dos colaboradores do repositorio.

**Comment by avelinorios** [comment]
Problema solucionado. Era porque tenía 2 correos asociados a esta cuenta y git no detectaba el correcto. Ahora debería de estar todo bien.

**Comment by lauramcastro** [comment]
Bien, cuando consideréis que el problema está resuelto, podéis cerrar la issue.
