### ISSUE TITLE
obtenerListaReproduccion() en Contenidos de carácter individual.

### ISSUE THREAD

**Issue by elenamdf** [angelcastro2/PracticaVVS#3]
Hemos detectado en vuestras implementaciones de Canción y Anuncio que el desarrollo del método de obtenerListaReproduccion() es errónea. 
Lo mismo sucede con la de buscar(String subcadena). 

El comportamiento que debe seguir es el especificado por Laura en el foro:

"O método obtenerListaReproducción() nos Contenidos de carácter "individual" (canción e anuncio) debe devolver unha estrutura de datos (colección, array, lista... de novo, a que resulte máis axeitada dependendo da linguaxe que empreguedes) que só conterá un elemento: a propia canción ou anuncio. O método buscar, como indica a nota no diagrama, busca no título, e devolve, igual que obtenerListaReproducción(), unha estrutura de datos coa canción/anuncio se é que a canción/anuncio ten un título que cadre coa búsqueda".

Con vuestra implementación os dejamos que penséis qué sucede cuando buscáis repetidas veces "PUBLI" en la clase Anuncio. ¿Qué pasa a suceder con la Lista de Reproducción?

**Comment by elenamdf** [comment]
He estado echando un vistazo a vuestros commits y a las diferentes versiones y tenéis alguna versión anterior en la que lo estabais realizando de manera correcta, por si os es más fácil.

**Comment by angelcastro2** [comment]
Arreglado
