### ISSUE TITLE
Fallo en ServidorConRespaldo

### ISSUE THREAD

**Issue by mateof** [angelcastro2/PracticaVVS#5]
Cando intentas buscar algo que non existe no servidor principal valeiro e con un token non válido, prodúcese un erro.

A intuición dime que o erro se produce por mor de que intenta meter un anuncio dentro da lista pero o servidor non ten ningún accesible.

**Comment by pedrofl** [comment]
Efectivamente, había un erro no servidor simple cando devolve una lista sen contidos.
Correxido o problema.

Grazas polo reporte.
