### ISSUE TITLE
No existe Token especial o de administrador.

### ISSUE THREAD

**Issue by elenamdf** [angelcastro2/PracticaVVS#6]
En el Servidor, la funcionalidad de agregar y eliminar contenidos en él sólo es válida en el momento en el que se le pasa un token especial que no caduca, un token equivalente a un administrador.

En vuestro caso, estáis comprobando (si no me equivoco) si existe en la lista de los tokens que ya tenéis admitidos por el servidor, y no existe tal token especial.

**Comment by pedrofl** [comment]
Efectivamente, el token especial no estaba implementado. El issue ya está corregido.
Gracias por el reporte.
