### ISSUE TITLE
Participación desequilibrada

### ISSUE THREAD

**Issue by lauramcastro** [angelcastro2/PracticaVVS#7]
Animade a @pedrofl a incrementar o seu número de commits no proxecto.

**Comment by avelinorios** [comment]
Buenas tardes, respecto a la participación de @pedrofl debo decir que es equitativa a la de @angelcastro2 y mía. Cierto que el número de commits es menor pero si nos fijamos en el número de líneas modificadas de los tres del grupo:
Pedro: +616
Ángel: +568
Avelino: +957
