### ISSUE TITLE
mejorar cobertura en servidorGenerico

### ISSUE THREAD

**Issue by angelcastro2** [angelcastro2/PracticaVVS#9]
metodos: alta, baja, eliminar y probar si se puede mejorar la de obtenerAnuncio.

**Comment by pedrofl** [comment]
Cobertura mejorada en servidorgenerico y Token. 
No se ha podido obtener un 100% de covertura en la clase Token porque depende de una cadena aleatoria, lo que hace que la funcion anadirToken sea imposible de predecir.
